// Generated by https://quicktype.io

// prettier-ignore
export interface LSP3ProfileJSON {
    LSP3Profile: LSP3Profile;
}

// prettier-ignore
export interface LSP3Profile {
    name:            string;
    description:     string;
    profileImage:    Image[];
    backgroundImage: Image[];
    tags:            string[];
    links:           Link[];
}

// prettier-ignore
export interface Link {
    title:          string;
    url:            string;
}

// prettier-ignore
export interface Image {
    width:        number;
    height:       number;
    hashFunction: string;
    hash:         string;
    url:          string;
}
