// Generated by https://quicktype.io

// prettier-ignore
export interface LSP3ProfileJSON {
    LSP3Profile: LSP3Profile;
}

// prettier-ignore
export interface LSP3Profile {
    name:            string;
    description:     string;
    profileImage:    LSP3ProfileImage[];
    backgroundImage: LSP3ProfileImage[];
    tags:            string[];
    links:           LSP3ProfileLink[];
}

// prettier-ignore
export interface LSP3ProfileLink {
    title:          string;
    url:            string;
}

// prettier-ignore
export interface LSP3ProfileImage {
    width:        number;
    height:       number;
    hashFunction: string;
    hash:         string;
    url:          string;
}
