name: Create GitHub release and publish to NPM

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: release
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@lukso'
          cache: 'npm'

      - name: 🧰 Install
        run: npm ci

      - name: 💅 Lint
        run: npm run lint

      - name: 🛠 Build
        run: npm run build

      - name: 🎯 Test
        run: npm run generate-types && npm run test

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: '@lukso/lsp-factory.js'
          bump-minor-pre-major: true
          default-branch: main

      - name: 🔍 Check if version changed
        uses: EndBug/version-check@v2
        if: github.event_name == 'push'
        id: check

      - name: 🔄 Check if should release
        run: echo "SHOULD_RELEASE=${{ steps.check.outputs.changed == 'true' }}" >> $GITHUB_ENV

      - name: 📦 Publish to NPM
        if: env.SHOULD_RELEASE == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
